on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: .NET setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - run: dotnet build -c Release
      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx.json

      - name: Upload GitHub pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site/

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
